# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Geopriv
                                 A QGIS plugin
 A set of location privacy tools for geographic data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-01-24
        copyright            : (C) 2019 by Juan Duque, Angelly Pugliese
        email                : pjduque@uninorte.edu.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Geopriv class from file Geopriv.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geoprivacy import Geopriv
    return Geopriv(iface)
